### ISSUE TITLE
Pty.close() doesn't stop the process

### ISSUE THREAD

**Issue by trofimander** [jawi/JPty#1]
1) I create Pty by JPty.execInPTY(command, arguments, environment).
2) I invoke Pty.close() method

Result: Slave fd isn't closed, process isn't stopped, Pty.waitFor hangs
Expected: Process is stopped, Pty.waitFor returns exit code.

**Comment by jawi** [comment]
The problem is probably because the child process is probably still running. I've pushed a couple of changes the will terminate a running child process in case the PTY is closed.  
If this resolves your issue, you can close this issue.

Thanks for reporting this!

**Comment by trofimander** [comment]
It works now! Thanks!
